### ISSUE TITLE
Unable to Deploy On Heroku

### ISSUE THREAD

**Issue by this-is-space** [Paddy-Pyker/BotsApp-MD#2]
Even After Scanning the QR and All Stuff I am unable to deploy on heroku

**Comment by paddy-pyker** [comment]
Can you show some logs output of the error

**Comment by this-is-space** [comment]
2022-02-15T10:04:19.450628+00:00 heroku[botsapp.1]: Process exited with status 1
2022-02-15T10:04:19.280560+00:00 app[botsapp.1]: Error: ENOENT: no such file or directory, open '/etc/botsapp-md/auth_info_multi.json'
2022-02-15T10:04:19.280567+00:00 app[botsapp.1]:     at Object.openSync (node:fs:585:3)
2022-02-15T10:04:19.280568+00:00 app[botsapp.1]:     at writeFileSync (node:fs:2155:35)
2022-02-15T10:04:19.280568+00:00 app[botsapp.1]:     at saveState (/BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:120:9)
2022-02-15T10:04:19.280569+00:00 app[botsapp.1]:     at Object.set (/BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:157:21)
2022-02-15T10:04:19.280569+00:00 app[botsapp.1]:     at assertingPreKeys (/BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:178:30)
2022-02-15T10:04:19.280570+00:00 app[botsapp.1]:     at uploadPreKeys (/BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:185:15)
2022-02-15T10:04:19.280570+00:00 app[botsapp.1]:     at WebSocket.<anonymous> (/BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:421:19)
2022-02-15T10:04:19.280570+00:00 app[botsapp.1]:     at WebSocket.emit (node:events:520:28)
2022-02-15T10:04:19.280571+00:00 app[botsapp.1]:     at WebSocket.emit (node:domain:475:12)
2022-02-15T10:04:19.280571+00:00 app[botsapp.1]:     at /BotsApp-MD/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:229:35 {
2022-02-15T10:04:19.280572+00:00 app[botsapp.1]:   errno: -2,
2022-02-15T10:04:19.280572+00:00 app[botsapp.1]:   syscall: 'open',
2022-02-15T10:04:19.280573+00:00 app[botsapp.1]:   code: 'ENOENT',
2022-02-15T10:04:19.280573+00:00 app[botsapp.1]:   path: '/etc/botsapp-md/auth_info_multi.json'
2022-02-15T10:04:19.280573+00:00 app[botsapp.1]: }
2022-02-15T10:04:19.304194+00:00 app[botsapp.1]: npm notice 
2022-02-15T10:04:19.304333+00:00 app[botsapp.1]: npm notice New minor version of npm available! 8.4.1 -> 8.5.0
2022-02-15T10:04:19.304635+00:00 app[botsapp.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
2022-02-15T10:04:19.304745+00:00 app[botsapp.1]: npm notice Run `npm install -g npm@8.5.0` to update!
2022-02-15T10:04:19.305003+00:00 app[botsapp.1]: npm notice

**Comment by paddy-pyker** [comment]
Did you use the docker approach?

**Comment by paddy-pyker** [comment]
Your issue is a result of file permissions
The auth_info_multi.json file cannot be created at /etc directory which is restricted in your case.

You should change the file location from '/etc/botsapp-md/auth_info_multi.json' to './auth_info_multi.json' in the main.ts file

**Comment by this-is-space** [comment]
As fas As I Know There is no file creation permission on Heroku

**Comment by paddy-pyker** [comment]
Make the changes highlighted earlier and see if it works

**Comment by paddy-pyker** [comment]
Use the link below to deploy your bot
[botsapp-md.herokuapp.com](http://botsapp-md.herokuapp.com)

**Comment by this-is-space** [comment]
I want to host on my heroku account ...
